import type { Metadata, Viewport } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { RoleProvider } from "@/components/role/RoleProvider";
import Sidebar from "@/components/Sidebar";
import { PageTransition } from "@/components/animate/PageTransition";
import { CommandMenu } from "@/components/CommandMenu";
import { ToastProvider } from "@/components/ui/Toast";
import { DensityProvider } from "@/components/prefs/DensityProvider";
import { NotificationProvider } from "@/components/notifications/NotificationProvider";
import { AssistantDrawer } from "@/components/assistant/AssistantDrawer";
import { MessageCenterProvider } from "@/context/MessageCenterContext";
import { NewsCenterProvider } from "@/context/NewsCenterContext";
import TopbarActions from "@/components/topbar/TopbarActions";
import MessageCenterSheet from "@/components/topbar/MessageCenterSheet";
import NewsCenterSheet from "@/components/topbar/NewsCenterSheet";
import MobileSidebar from "@/components/topbar/MobileSidebar";
import SearchBar from "@/components/topbar/SearchBar";
import DashboardSwitcher from "@/components/topbar/DashboardSwitcher";
import PersonaSummary from "@/components/topbar/PersonaSummary";
import DynamicAgentsProvider from "@/components/niche/DynamicAgentsProvider";

const inter = Inter({ subsets: ["latin"] });
const plex = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Sentient Dashboard",
  description: "Generated by Inova AI Solutions",
  icons: { icon: "/og.svg" },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${plex.className} min-h-screen flex flex-col`}>
        <ToastProvider>
        <DensityProvider>
        <RoleProvider>
        <NotificationProvider>
        <MessageCenterProvider>
        <NewsCenterProvider>
        <DynamicAgentsProvider>
          <a href="#main" className="sr-only focus:not-sr-only fixed left-2 top-2 z-50 rounded-control bg-surface px-3 py-2 text-sm text-ink shadow-elevation-sm outline outline-2 outline-primary outline-offset-2">Skip to content</a>
          <div className="flex-1 lg:flex">
            <Sidebar />
            <main id="main" className="relative flex-1 pb-16">
              <header className="sticky top-0 z-40 w-full border-b border-line/60 bg-white">
                <div className="flex items-center justify-between gap-3 px-4 py-5">
                  <div className="flex items-center gap-2 flex-1">
                    <SearchBar />
                  </div>
                  <div className="shrink-0 flex items-center gap-2">
                    <TopbarActions />
                    {/* Hamburger on mobile/tablet to the right of messaging button */}
                    <MobileSidebar />
                    <div className="hidden md:block">
                      <PersonaSummary />
                    </div>
                  </div>
                </div>
              </header>
              <PageTransition>{children}</PageTransition>
            </main>
          </div>
          <CommandMenu />
          <AssistantDrawer />
          <MessageCenterSheet />
          <NewsCenterSheet />
        </DynamicAgentsProvider>
        </NewsCenterProvider>
        </MessageCenterProvider>
        </NotificationProvider>
        </RoleProvider>
        </DensityProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
