export type NicheKey = "insurance-dashboard" | "healthcare-dashboard" | "fintech-dashboard" | "hospitality-dashboard" | "retail-dashboard";

export type NicheConfig = {
  slug: NicheKey;
  title: string;
  roles: string[]; // local role labels (display only for now)
  storageKey: string; // namespaced agent state key
  // Agents from spreadsheet that have BLDR URLs (ids from src/mock/agents.ts)
  agentIds: string[];
  // Which of those should be online on first visit (only used when no saved state exists)
  baselineOnlineIds: string[];
  menu: { label: string; href: string }[];
  // Optional per-role menus; when present, sidebar will use these instead of `menu`
  menusByRole?: Record<string, { label: string; href: string }[]>;
};

const BLDR_IDS = [] as const;

export const NICHES: Record<NicheKey, NicheConfig> = {
  "insurance-dashboard": {
    slug: "insurance-dashboard",
    title: "Insurance Dashboard",
    roles: ["Claims Adjuster", "Underwriter", "Customer", "Admin"],
    storageKey: "su_agents_state__insurance-dashboard",
    agentIds: [
      "claims-intake-triage",
      "fnol-extractor",
      "fraud-signal-detector",
      "subrogation-recommender",
      "settlement-optimizer",
      "underwriting-risk-scorer",
      "policy-document-drafter",
      "regulatory-reporter",
      "customer-communication-composer",
      "coverage-gap-advisor",
    ],
    baselineOnlineIds: [],
    menu: [
      { label: "Dashboard", href: "/insurance-dashboard" },
      { label: "Policies", href: "/insurance-dashboard/policies" },
      { label: "Claims", href: "/insurance-dashboard/claims" },
      { label: "Risk Analytics", href: "/insurance-dashboard/risk-analytics" },
      { label: "Agents", href: "/insurance-dashboard/agents" },
    ],
    menusByRole: {
      "Claims Adjuster": [
        { label: "Dashboard", href: "/insurance-dashboard" },
        { label: "Open New Claim", href: "/insurance-dashboard/claims/new" },
        { label: "Claims Queue", href: "/insurance-dashboard/claims" },
        { label: "Claim Detail View", href: "/insurance-dashboard/claim-detail" },
        { label: "Customer Communication", href: "/insurance-dashboard/communications" },
        { label: "Payments & Settlements", href: "/insurance-dashboard/payments-settlements" },
        { label: "Agents", href: "/insurance-dashboard/agents" },
      ],
      "Underwriter": [
        { label: "Dashboard", href: "/insurance-dashboard" },
        { label: "Applications Queue", href: "/insurance-dashboard/underwriting/applications" },
        { label: "New Application", href: "/insurance-dashboard/underwriting/new-application" },
        { label: "Risk Assessment", href: "/insurance-dashboard/underwriting/risk" },
        { label: "Policy Approval / Pricing", href: "/insurance-dashboard/underwriting/approval-pricing" },
        { label: "Agents", href: "/insurance-dashboard/agents" },
      ],
      "Customer": [
        { label: "Dashboard", href: "/insurance-dashboard" },
        { label: "File a Claim", href: "/insurance-dashboard/customer/file-claim" },
        { label: "My Claims", href: "/insurance-dashboard/customer/claims" },
        { label: "Billing & Payments", href: "/insurance-dashboard/customer/billing" },
        { label: "My Policies", href: "/insurance-dashboard/customer/policies" },
        { label: "Agents", href: "/insurance-dashboard/agents" },
      ],
      "Admin": [
        { label: "Dashboard", href: "/insurance-dashboard" },
        { label: "User Management", href: "/insurance-dashboard/admin/users" },
        { label: "Claims Oversight", href: "/insurance-dashboard/admin/claims-oversight" },
        { label: "Compliance & Reporting", href: "/insurance-dashboard/admin/compliance-reporting" },
        { label: "Agents", href: "/insurance-dashboard/agents" },
        { label: "Agent Monitor", href: "/insurance-dashboard/admin/monitor" },
        { label: "Agent Management", href: "/insurance-dashboard/admin/agents" },
      ],
    },
  },
  "healthcare-dashboard": {
    slug: "healthcare-dashboard",
    title: "Healthcare Dashboard",
    roles: ["Doctor", "Patient", "Admin"],
    storageKey: "su_agents_state__healthcare-dashboard",
    agentIds: [
      "care-plan-builder",
      "appointment-scheduler",
      "medication-safety-checker",
      "lab-trends-explainer",
      "clinical-note-summarizer",
      "patient-education-coach",
      "coverage-billing-assistant",
      "facility-capacity-monitor",
      "referral-coordinator",
      "hipaa-compliance-reporter",
    ],
    baselineOnlineIds: [],
    menu: [
      { label: "Dashboard", href: "/healthcare-dashboard" },
      { label: "Appointments", href: "/healthcare-dashboard/appointments" },
      { label: "Care Plans", href: "/healthcare-dashboard/care-plans" },
      { label: "Clinical Analytics", href: "/healthcare-dashboard/clinical-analytics" },
      { label: "Agents", href: "/healthcare-dashboard/agents" },
    ],
    menusByRole: {
      "Doctor": [
        { label: "Dashboard", href: "/healthcare-dashboard" },
        { label: "Patient Overview", href: "/healthcare-dashboard/patient-overview" },
        { label: "Appointments", href: "/healthcare-dashboard/appointments" },
        { label: "Medical Records", href: "/healthcare-dashboard/records" },
        { label: "Lab & Diagnostics", href: "/healthcare-dashboard/labs" },
        { label: "Agents", href: "/healthcare-dashboard/agents" },
      ],
      "Patient": [
        { label: "Dashboard", href: "/healthcare-dashboard" },
        { label: "My Health Summary", href: "/healthcare-dashboard/my-health-summary" },
        { label: "Appointments", href: "/healthcare-dashboard/appointments" },
        { label: "Medications", href: "/healthcare-dashboard/medications" },
        { label: "Lab Results", href: "/healthcare-dashboard/lab-results" },
        { label: "Agents", href: "/healthcare-dashboard/agents" },
      ],
      "Admin": [
        { label: "Dashboard", href: "/healthcare-dashboard" },
        { label: "User Management", href: "/healthcare-dashboard/admin/users" },
        { label: "Facility Management", href: "/healthcare-dashboard/admin/facilities" },
        { label: "Scheduling & Appointments", href: "/healthcare-dashboard/admin/scheduling" },
        { label: "Compliance & Reporting", href: "/healthcare-dashboard/admin/compliance-reporting" },
        { label: "Billing & Claims", href: "/healthcare-dashboard/admin/billing-claims" },
        { label: "Agents", href: "/healthcare-dashboard/agents" },
        { label: "Agent Monitor", href: "/healthcare-dashboard/admin/monitor" },
        { label: "Agent Management", href: "/healthcare-dashboard/admin/agents" },
      ],
    },
  },
  "fintech-dashboard": {
    slug: "fintech-dashboard",
    title: "Fintech Dashboard",
    roles: ["Portfolio Manager", "Customer", "Risk Officer", "Admin"],
    storageKey: "su_agents_state__fintech-dashboard",
    agentIds: [
      "portfolio-insights-copilot",
      "execution-monitor",
      "risk-breach-sentinel",
      "liquidity-cash-forecast",
      "compliance-reporter",
      "kyc-aml-analyzer",
      "billing-reconciliation",
      "customer-spend-insights",
      "investment-goal-planner",
      "product-ops-insights",
    ],
    baselineOnlineIds: [],
    menu: [
      { label: "Dashboard", href: "/fintech-dashboard" },
      { label: "Accounts", href: "/fintech-dashboard/accounts" },
      { label: "Payments", href: "/fintech-dashboard/payments" },
      { label: "Risk & Compliance", href: "/fintech-dashboard/risk-compliance" },
      { label: "Agents", href: "/fintech-dashboard/agents" },
    ],
    menusByRole: {
      "Portfolio Manager": [
        { label: "Dashboard", href: "/fintech-dashboard" },
        { label: "Portfolio Overview", href: "/fintech-dashboard/portfolio" },
        { label: "Positions & Holdings", href: "/fintech-dashboard/positions" },
        { label: "Performance & Analytics", href: "/fintech-dashboard/performance" },
        { label: "Transactions", href: "/fintech-dashboard/transactions" },
        { label: "Agents", href: "/fintech-dashboard/agents" },
      ],
      "Customer": [
        { label: "Dashboard", href: "/fintech-dashboard" },
        { label: "My Accounts", href: "/fintech-dashboard/customer/accounts" },
        { label: "Transactions", href: "/fintech-dashboard/customer/transactions" },
        { label: "Investments", href: "/fintech-dashboard/customer/investments" },
        { label: "Reports", href: "/fintech-dashboard/customer/reports" },
        { label: "Agents", href: "/fintech-dashboard/agents" },
      ],
      "Risk Officer": [
        { label: "Dashboard", href: "/fintech-dashboard" },
        { label: "Risk Overview", href: "/fintech-dashboard/risk/overview" },
        { label: "Exposures", href: "/fintech-dashboard/risk/exposures" },
        { label: "Alerts & Breaches", href: "/fintech-dashboard/risk/alerts" },
        { label: "Reports", href: "/fintech-dashboard/risk/reports" },
        { label: "Agents", href: "/fintech-dashboard/agents" },
      ],
      "Admin": [
        { label: "Dashboard", href: "/fintech-dashboard" },
        { label: "User Management", href: "/fintech-dashboard/admin/users" },
        { label: "Product Management", href: "/fintech-dashboard/admin/products" },
        { label: "Risk Controls", href: "/fintech-dashboard/admin/risk-controls" },
        { label: "Compliance & Audits", href: "/fintech-dashboard/admin/compliance" },
        { label: "Billing", href: "/fintech-dashboard/admin/billing" },
        { label: "Agent Monitor", href: "/fintech-dashboard/admin/monitor" },
        { label: "Agent Management", href: "/fintech-dashboard/admin/agents" },
        { label: "Agents", href: "/fintech-dashboard/agents" },
      ],
    },
  },
  "hospitality-dashboard": {
    slug: "hospitality-dashboard",
    title: "Hospitality Dashboard",
    roles: ["Front Desk", "Guest", "Ops Manager", "Admin"],
    storageKey: "su_agents_state__hospitality-dashboard",
    agentIds: [
      "reservation-optimizer",
      "dynamic-pricing-revenue",
      "housekeeping-orchestrator",
      "guest-concierge",
      "upsell-recommender",
      "loyalty-recommender",
      "service-request-router",
      "property-ops-monitor",
      "review-sentiment-analyzer",
      "payment-exception-resolver",
    ],
    baselineOnlineIds: [],
    menu: [
      { label: "Dashboard", href: "/hospitality-dashboard" },
      { label: "Reservations", href: "/hospitality-dashboard/reservations" },
      { label: "Guest Experience", href: "/hospitality-dashboard/guest-experience" },
      { label: "Ops Analytics", href: "/hospitality-dashboard/ops-analytics" },
      { label: "Agents", href: "/hospitality-dashboard/agents" },
    ],
    menusByRole: {
      "Front Desk": [
        { label: "Dashboard", href: "/hospitality-dashboard" },
        { label: "Reservations", href: "/hospitality-dashboard/reservations" },
        { label: "Check-ins & Check-outs", href: "/hospitality-dashboard/checkins-checkouts" },
        { label: "Guest Directory", href: "/hospitality-dashboard/guest-directory" },
        { label: "Housekeeping Status", href: "/hospitality-dashboard/housekeeping-status" },
        { label: "Agents", href: "/hospitality-dashboard/agents" },
      ],
      "Guest": [
        { label: "Dashboard", href: "/hospitality-dashboard" },
        { label: "My Stays", href: "/hospitality-dashboard/my-stays" },
        { label: "Services & Requests", href: "/hospitality-dashboard/services-requests" },
        { label: "Payments & Billing", href: "/hospitality-dashboard/payments-billing" },
        { label: "Loyalty & Rewards", href: "/hospitality-dashboard/loyalty-rewards" },
        { label: "Agents", href: "/hospitality-dashboard/agents" },
      ],
      "Admin": [
        { label: "Dashboard", href: "/hospitality-dashboard" },
        { label: "User Management", href: "/hospitality-dashboard/admin/users" },
        { label: "Property Management", href: "/hospitality-dashboard/admin/property" },
        { label: "Revenue Management", href: "/hospitality-dashboard/admin/revenue" },
        { label: "Compliance", href: "/hospitality-dashboard/admin/compliance" },
        { label: "Billing", href: "/hospitality-dashboard/admin/billing" },
        { label: "Agents", href: "/hospitality-dashboard/agents" },
        { label: "Agent Monitor", href: "/hospitality-dashboard/admin/monitor" },
        { label: "Agent Management", href: "/hospitality-dashboard/admin/agents" },
      ],
    },
  },
  "retail-dashboard": {
    slug: "retail-dashboard",
    title: "Retail Dashboard",
    roles: ["Store Manager", "Customer", "Merchandiser", "Admin"],
    storageKey: "su_agents_state__retail-dashboard",
    agentIds: [
      "demand-forecasting",
      "price-optimizer",
      "promotion-recommender",
      "inventory-replenishment",
      "supplier-risk-monitor",
      "staffing-planner",
      "returns-analyzer",
      "basket-insights",
      "customer-support-copilot",
      "store-performance-explainer",
    ],
    baselineOnlineIds: [],
    menu: [
      { label: "Dashboard", href: "/retail-dashboard" },
      { label: "Inventory", href: "/retail-dashboard/inventory" },
      { label: "Sales Analytics", href: "/retail-dashboard/sales-analytics" },
      { label: "Promotions", href: "/retail-dashboard/promotions" },
      { label: "Agents", href: "/retail-dashboard/agents" },
    ],
    menusByRole: {
      "Store Manager": [
        { label: "Dashboard", href: "/retail-dashboard" },
        { label: "Sales Overview", href: "/retail-dashboard/sales-overview" },
        { label: "Inventory", href: "/retail-dashboard/inventory" },
        { label: "Staff & Shifts", href: "/retail-dashboard/staff-shifts" },
        { label: "Store Performance", href: "/retail-dashboard/store-performance" },
        { label: "Agents", href: "/retail-dashboard/agents" },
      ],
      "Customer": [
        { label: "Dashboard", href: "/retail-dashboard" },
        { label: "Orders", href: "/retail-dashboard/orders" },
        { label: "Wishlist", href: "/retail-dashboard/wishlist" },
        { label: "Rewards", href: "/retail-dashboard/rewards" },
        { label: "Agents", href: "/retail-dashboard/agents" },
      ],
      "Merchandiser": [
        { label: "Dashboard", href: "/retail-dashboard" },
        { label: "Product Catalog", href: "/retail-dashboard/product-catalog" },
        { label: "Pricing & Promotions", href: "/retail-dashboard/pricing-promotions" },
        { label: "Supplier Management", href: "/retail-dashboard/suppliers" },
        { label: "Inventory Planning", href: "/retail-dashboard/inventory-planning" },
        { label: "Agents", href: "/retail-dashboard/agents" },
      ],
      "Admin": [
        { label: "Dashboard", href: "/retail-dashboard" },
        { label: "User Management", href: "/retail-dashboard/admin/users" },
        { label: "Product Management", href: "/retail-dashboard/admin/products" },
        { label: "Inventory Oversight", href: "/retail-dashboard/admin/inventory" },
        { label: "Sales & Revenue", href: "/retail-dashboard/admin/sales" },
        { label: "Compliance", href: "/retail-dashboard/admin/compliance" },
        { label: "Agents", href: "/retail-dashboard/agents" },
        { label: "Agent Monitor", href: "/retail-dashboard/admin/monitor" },
        { label: "Agent Management", href: "/retail-dashboard/admin/agents" },
      ],
    },
  },
};

export const ALL_BDLR_IDS = BLDR_IDS as unknown as string[];


